web/router.ex
defmodule ElixirStatus.Router do
  use ElixirStatus.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :assign_current_user
  end

  scope "/", ElixirStatus do
    pipe_through :browser # Use the default browser stack

    get "/", PostingController, :index
    get "/rss", FeedController, :rss
    get "/about", PageController, :about

    get "/rss/avatar/:user_name", FeedController, :avatar
    get "/avatar/github/:user_name", PageController, :avatar

    get "/postings/preview", PostingController, :preview, as: :preview_posting
    post "/postings/unpublish/:id", PostingController, :unpublish
    resources "/postings", PostingController
    get "/p/:permalink", PostingController, :show, as: :permalink_posting
    get "/p/edit/:permalink", PostingController, :edit

    get "/edit_profile", UserController, :edit, as: :edit_user
    put "/update_profile", UserController, :update, as: :update_user

    get "/=:uid", ShortLinkController, :show
  end

  scope "/auth", alias: ElixirStatus do
    pipe_through :browser

    get "/", GitHubAuthController, :sign_in
    get "/sign_out", GitHubAuthController, :sign_out
    get "/callback", GitHubAuthController, :callback
  end

  scope "/admin", alias: ElixirStatus.Admin do
    pipe_through :browser

    get "/", OverviewController, :index
    get "/impressions", ImpressionController, :index
    get "/users", UserController, :index
    get "/postings", PostingController, :index, as: :admin_posting
    get "/postings/recent", PostingController, :recent
  end

  # Other scopes may use custom stacks.
  scope "/impression", ElixirStatus do
    pipe_through :api

    post "/", ImpressionController, :create, as: :impression
  end

  # Other scopes may use custom stacks.
  scope "/api", ElixirStatus do
    pipe_through :api

    post "/external", ImpressionController, :external, as: :external
    post "/postings", ImpressionController, :postings, as: :postings
  end

  # Fetch the current user from the session and add it to `conn.assigns`. This
  # will allow you to have access to the current user in your views with
  # `@current_user`.
  defp assign_current_user(conn, _) do
    user_id = get_session(conn, :current_user_id)
    assign(conn, :current_user, ElixirStatus.Admin.UserController.find_by_id(user_id))
  end

  # Other scopes may use custom stacks.
  # scope "/api", ElixirStatus do
  #   pipe_through :api
  # end
end

web/templates/page/about.html.eex
<h2>What is ElixirStatus?</h2>


<p>ElixirStatus is a site <a href="https://github.com/rrrene/elixirstatus-web/network/members">built by the community</a> to provide <strong><em>an outlet where we can post stuff we have created</em></strong>.</p>

<p>It is not so much a link sharing platform where you post stuff you <em>find</em>, but more of a creator-hub where <strong><em>you can post when you have something new to announce</em></strong>, like:</p>

<ul>
  <li>a project</li>
  <li>a blog post</li>
  <li>a version update</li>
  <li>an episode of your podcast</li>
  <li>or if you are organizing a meetup/conference</li>
</ul>

<p><strong><em>Your announcement will then appear</em></strong> on this website, in <a href="http://elixirstatus.com/rss">RSS</a>, on <a href="https://twitter.com/elixirstatus">Twitter</a> and <a href="https://www.reddit.com/r/elixir/">/r/elixir</a>.</p>

<p>The idea is to have something akin to what <a href="http://rubyflow.com/">RubyFlow</a> is for Ruby, but bringing the Elixir community's ideas to the table.</p>

<p>Last but not least, ElixirStatus is a web app written in <strong><em>Elixir+Phoenix running in production</em></strong>.</p>

<p>Together with sites like <a href="http://jobs.elixirdose.com/">Elixir Jobs</a> it is <strong><em>intended to serve as a case study</em></strong> for the community, so <strong><em>you can point your boss to these sites</em></strong> if he or she wants to see "proof" that this "Elixir thing" is actually a viable alternative to Ruby/Python/Node when building the next web project.</p>

web/templates/page/announcement.html.eex
<div class="post">
  <div class="post-avatar">
    <div class="image " style="background-image: url(/images/avatar_rrrene.jpg)"></div>
  </div>
  <h1 class="post-title">
    <a href="/">
      elixirstatus.com
    </a>
  </h1>

  <span class="post-meta">24 Jun 2015 by <a href="https://twitter.com/rrrene" target="_blank">@rrrene</a></span>

  <div class="post-body">
    <p>
      Hi there,
    </p>
    <p>
      I'm @rrrene, maintainer of <a href="http://inch-ci.org/" target="_blank">Inch CI</a> and <a href="https://github.com/rrrene/inch_ex" target="_blank">InchEx</a>.
    </p>
    <p>
      This page exists because <strong><em>I think we need a site</em></strong> where people can post what they made in Elixir, simliar to <a href="http://rubyflow.com/" target="_blank">RubyFlow</a> for Ruby, <strong><em>where annoucements don't disappear after a day</em></strong> like on Twitter. A service that is build in Elixir, that is Open Source and integrates nicely with the existing ecosystem.
    </p>
    <p>
      I think a service like that, if done right, will eventually be of great use <strong><em>to encourage people to contribute to the Elixir community.</em></strong>
    </p>
    <p>
      You can read the wordy reasoning behind this in the <a href="http://trivelop.de/2015/06/26/announcing-elixirstatus/" target="_blank">announcement</a>.
    </p>
    <p>
      Ah, nearly forgot: <strong><em>I want to build this site</em></strong> with your help, <a href="https://github.com/rrrene/elixirstatus-web" target="_blank">right here</a>.
    </p>
  </div>
</div>

<hr>

web/templates/page/index.html.eex
<div class="posts">
  <%= if logged_in?(@conn) do %>

    <%= render ElixirStatus.PageView, "index_logged_in.html", current_user: @current_user, conn: @conn %>

  <% else %>

    <%= render ElixirStatus.PageView, "announcement.html", current_user: @current_user, conn: @conn %>
    <%= render ElixirStatus.PageView, "index_not_logged_in.html", conn: @conn %>

  <% end %>
</div>

web/templates/page/index_logged_in.html.eex
<div class="logged_in">
  <div class="post">
    <div class="post-author">
      <div class="avatar " style="background-image: url(<%=# @current_user.avatar_url %>)"></div>
    </div>
    <h1 class="post-title">
      Welcome, <%= @current_user.user_name %>!
    </h1>

    <div class="post-body">
      <p>
        You successfully signed in and will be among the first to know when this site becomes useful!
        Let's get the word out:
      </p>
      <p>
        <blockquote>An upcoming announcement service for Elixir: elixirstatus.com</blockquote>
      </p>
      <p>
        <a class="btn btn-tweet" href="https://twitter.com/intent/tweet?hashtags=elixirlang&text=An upcoming announcement service for Elixir: elixirstatus.com" target="_blank"><img src="https://twemoji.maxcdn.com/36x36/1f423.png" style="height: 18px; vertical-align: middle; display: inline-block;"> Tweet this</a>
      </p>
    </div>
  </div>
</div>

web/templates/page/index_not_logged_in.html.eex
<a class="btn btn-tweet btn-lg" href="<%= git_hub_auth_path @conn, :sign_in %>">
  <img src="https://twemoji.maxcdn.com/36x36/2764.png" style="height: 18px; vertical-align: middle; display: inline-block;"> Join the private beta
</a>
<small>Signs you in via GitHub, pre-registers your GitHub username.</small>