web/router.ex
defmodule ElixirStatus.Router do
  use ElixirStatus.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :assign_current_user
  end

  scope "/", ElixirStatus do
    pipe_through :browser # Use the default browser stack

    get "/", PostingController, :index
    get "/rss", FeedController, :rss
    get "/about", PageController, :about

    get "/rss/avatar/:user_name", FeedController, :avatar
    get "/avatar/github/:user_name", PageController, :avatar

    get "/postings/preview", PostingController, :preview, as: :preview_posting
    post "/postings/unpublish/:id", PostingController, :unpublish
    resources "/postings", PostingController
    get "/p/:permalink", PostingController, :show, as: :permalink_posting
    get "/p/edit/:permalink", PostingController, :edit

    get "/edit_profile", UserController, :edit, as: :edit_user
    put "/update_profile", UserController, :update, as: :update_user

    get "/=:uid", ShortLinkController, :show
  end

  scope "/auth", alias: ElixirStatus do
    pipe_through :browser

    get "/", GitHubAuthController, :sign_in
    get "/sign_out", GitHubAuthController, :sign_out
    get "/callback", GitHubAuthController, :callback
  end

  scope "/admin", alias: ElixirStatus.Admin do
    pipe_through :browser

    get "/", OverviewController, :index
    get "/impressions", ImpressionController, :index
    get "/users", UserController, :index
    get "/postings", PostingController, :index, as: :admin_posting
    get "/postings/recent", PostingController, :recent
  end

  # Other scopes may use custom stacks.
  scope "/impression", ElixirStatus do
    pipe_through :api

    post "/", ImpressionController, :create, as: :impression
  end

  # Other scopes may use custom stacks.
  scope "/api", ElixirStatus do
    pipe_through :api

    post "/external", ImpressionController, :external, as: :external
    post "/postings", ImpressionController, :postings, as: :postings
  end

  # Fetch the current user from the session and add it to `conn.assigns`. This
  # will allow you to have access to the current user in your views with
  # `@current_user`.
  defp assign_current_user(conn, _) do
    user_id = get_session(conn, :current_user_id)
    assign(conn, :current_user, ElixirStatus.Admin.UserController.find_by_id(user_id))
  end

  # Other scopes may use custom stacks.
  # scope "/api", ElixirStatus do
  #   pipe_through :api
  # end
end

web/models/posting.ex
defmodule ElixirStatus.Posting do
  use ElixirStatus.Web, :model

  schema "postings" do
    field :uid, :string
    field :permalink, :string
    field :title, :string
    field :text, :string
    field :scheduled_at, Timex.Ecto.DateTime
    field :published_at, Timex.Ecto.DateTime
    field :published_tweet_uid, :string
    field :public, :boolean, default: false

    timestamps

    belongs_to :user, ElixirStatus.User
  end

  @required_fields ~w(user_id uid permalink title text published_at public)
  @optional_fields ~w(published_tweet_uid scheduled_at)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> update_change(:title, &String.strip/1)
    |> validate_length(:title, min: 1)
    |> update_change(:text, &String.strip/1)
    |> validate_length(:text, min: 1)
  end
end

web/controllers/admin/posting_controller.ex
defmodule ElixirStatus.Admin.PostingController do
  use ElixirStatus.Web, :controller
  use Timex

  alias  ElixirStatus.Posting

  plug ElixirStatus.Plugs.Admin

  @layout {ElixirStatus.LayoutView, "admin.html"}

  def index(conn, params) do
    page = ElixirStatus.PostingController.get_all(params)
    count = Repo.one(from r in Posting,
                      where: r.public == ^true,
                      select: count(r.id))
    render conn, "index.html", layout: @layout,
                                count: count,
                                postings: page.entries,
                                page_number: page.page_number,
                                total_pages: page.total_pages
  end


  def recent(conn, _params) do
    from_date = Date.now
    until_date = days_earlier(28)
    query = from p in Posting,
                  where: p.public == ^true and
                  p.published_at <= ^from_date and p.published_at > ^until_date,
                  order_by: [desc: :published_at]
    postings = query |> Ecto.Query.preload(:user) |> Repo.all

    render conn, "recent.json", postings: postings
  end

  defp days_earlier(count) do
    Date.now
    |> Date.subtract(Time.to_timestamp(count, :days))
  end
end

web/controllers/posting_controller.ex
defmodule ElixirStatus.PostingController do
  use ElixirStatus.Web, :controller
  use Timex

  alias ElixirStatus.Publisher
  alias ElixirStatus.Posting

  @postings_per_page          20
  @just_created_timeout       60 # seconds
  @current_posting_assign_key :posting

  plug :load_posting when action in [:edit, :update, :delete, :show]

  plug ElixirStatus.Plugs.LoggedIn when action in [:new, :create, :edit, :update, :delete]
  plug ElixirStatus.Plugs.Admin when action in [:unpublish]
  plug ElixirStatus.Plugs.SameUserOrAdmin, @current_posting_assign_key when action in [:edit, :update, :delete]

  plug :scrub_params, "posting" when action in [:create, :update]

  def index(conn, params) do
    page = get_all(params)
    conn
    |> ElixirStatus.Impressionist.record("frontpage")
    |> render("index.html", postings: page.entries,
                            page_number: page.page_number,
                            total_pages: page.total_pages,
                            created_posting: load_created_posting(conn),
                            just_signed_in: params["just_signed_in"] == "true",
                            searching?: !is_nil(params["q"]),
                            search_query: params["q"],
                            changeset: Posting.changeset(%Posting{}))
  end

  def new(conn, _params) do
    render(conn, "new.html", changeset: Posting.changeset(%Posting{}))
  end

  def create(conn, %{"posting" => posting_params}) do
    posting_params =
      posting_params
      |> extract_valid_params
      |> to_create_params(conn)
    changeset = Posting.changeset(%Posting{}, posting_params)

    if changeset.valid? do
      posting = Repo.insert!(changeset)
      posting |> Publisher.after_create(Auth.current_user(conn).twitter_handle)

      conn
      |> put_session(:created_posting_uid, posting.uid)
      |> redirect(to: posting_path(conn, :index))
    else
      render(conn, "new.html", changeset: changeset)
    end
  end

  @preview_default_title "-- insert title --"
  @preview_default_text  "-- insert text --"

  def preview(conn, params) do
    render(conn, "preview.html",
            layout: {ElixirStatus.LayoutView, "blank.html"},
            posting: %Posting{
                      title: default(params["title"], @preview_default_title),
                      text: default(params["text"], @preview_default_text)
                    })
  end

  def default(nil, value), do: value
  def default("", value), do: value
  def default(value, _), do: value

  def show(conn, %{"permalink" => _}) do
    show(conn, %{"id" => current_posting(conn)})
  end

  def show(conn, %{"id" => _}) do
    posting = current_posting(conn)

    conn
    |> ElixirStatus.Impressionist.record("detail", "posting", posting.uid)
    |> render("show.html",  posting: posting,
                            created_posting: load_created_posting(conn),
                            prev_posting: load_prev_posting(posting),
                            next_posting: load_next_posting(posting))
  end

  def edit(conn, %{"permalink" => _}) do
    edit(conn, %{"id" => current_posting(conn)})
  end

  def edit(conn, %{"id" => _}) do
    posting = current_posting(conn)
    changeset = Posting.changeset(posting)
    render(conn, "edit.html", posting: posting, changeset: changeset)
  end

  def update(conn, %{"id" => id, "posting" => posting_params}) do
    posting = Repo.get!(Posting, id)
    posting_params = posting_params |> extract_valid_params
    changeset = Posting.changeset(posting, posting_params)

    if changeset.valid? do
      Repo.update!(changeset)
      |> Publisher.after_update

      conn
      |> put_flash(:info, "Posting updated successfully.")
      |> redirect(to: posting_path(conn, :index))
    else
      render(conn, "edit.html", posting: posting, changeset: changeset)
    end
  end

  def update_published_tweet_uid(posting, tweet_uid) do
    posting
    |> Posting.changeset(%{published_tweet_uid: tweet_uid})
    |> Repo.update!
  end

  def unpublish(conn, %{"id" => id}) do
    posting = Repo.get!(Posting, id)
    changeset = Posting.changeset(posting, %{public: false})

    if changeset.valid?, do: Repo.update!(changeset)

    conn
    |> redirect(to: posting_path(conn, :index))
  end

  def delete(conn, %{"id" => id}) do
    posting = Repo.get!(Posting, id)
    Repo.delete!(posting)

    conn
    |> put_flash(:info, "Posting deleted successfully.")
    |> redirect(to: posting_path(conn, :index))
  end

  defp load_posting(conn, _) do
    posting = case conn do
      %{params: %{"id" => id}} -> get_by_id(id)
      %{params: %{"permalink" => permalink}} -> get_by_permalink(permalink)
      _ -> nil
    end
    if is_nil(posting) || posting.public == false do
      conn
      |> put_status(:not_found)
      |> render(ElixirStatus.ErrorView, "404.html")
      |> halt
    else
      conn
      |> assign(@current_posting_assign_key, posting)
    end
  end

  defp load_prev_posting(posting) do
    query = from p in Posting,
                  where: p.public == ^true and
                          p.published_at < ^posting.published_at,
                  order_by: [desc: :published_at],
                  limit: 1
    query |> Ecto.Query.preload(:user) |> Repo.one
  end

  defp load_next_posting(posting) do
    query = from p in Posting,
                  where: p.public == ^true and
                          p.published_at > ^posting.published_at,
                  order_by: [asc: :published_at],
                  limit: 1
    query |> Ecto.Query.preload(:user) |> Repo.one
  end

  defp load_created_posting(conn) do
    uid = get_session(conn, :created_posting_uid)
    case load_created_posting_by_uid(uid)  do
      nil ->
        conn
        |> put_session(:created_posting_uid, nil)
        nil
      posting -> posting
    end
  end

  defp load_created_posting_by_uid(nil), do: nil

  defp load_created_posting_by_uid(uid) do
    posting = get_by_uid(uid)
    seconds_since_posting = Date.diff(posting.published_at, Date.now, :secs)
    if seconds_since_posting < @just_created_timeout do
      posting
    else
      nil
    end
  end

  defp current_posting(conn) do
    conn.assigns[@current_posting_assign_key]
  end

  defp extract_valid_params(%{"title" => title, "text" => text}) do
    %{"title" => title || "", "text" => text || ""}
  end
  defp extract_valid_params(%{"title" => title, "text" => text, "scheduled_at" => scheduled_at}) do
    %{"title" => title || "", "text" => text || "", "scheduled_at" => scheduled_at}
  end
  defp extract_valid_params(_) do
    %{}
  end

  defp to_create_params(params, conn) do
    uid = ElixirStatus.UID.generate(Posting)
    %{
      user_id: Auth.current_user(conn).id,
      uid: uid,
      permalink: Publisher.permalink(uid, params["title"]),
      text: params["text"],
      title: params["title"],
      scheduled_at: params["scheduled_at"],
      published_at: Date.now,
      public: true
    }
  end

  @doc "Returns the latest postings."
  def get_all(params \\ %{}) do
    params = Map.put(params, :page_size, @postings_per_page)
    query_for(params) |> Ecto.Query.preload(:user) |> Repo.paginate(params)
  end

  defp query_for(%{"q" => q}) do
    term = "%" <> String.replace(q, " ", "%") <> "%"
    from p in Posting, where: p.public == ^true and (like(p.title, ^term) or like(p.text, ^term)),
                        order_by: [desc: :published_at]
  end
  defp query_for(_) do
    from p in Posting, where: p.public == ^true,
                        order_by: [desc: :published_at]
  end

  defp get_by_id(id) do
    query = from(p in Posting, where: p.id == ^id)
    query |> Ecto.Query.preload(:user) |> Repo.one
  end

  defp get_by_permalink(permalink) do
    String.split(permalink, "-") |> Enum.at(0) |> get_by_uid
  end

  @doc "Returns the posting with the given +uid+."
  def get_by_uid(uid) do
    query = from(p in Posting, where: p.uid == ^uid)
    query |> Ecto.Query.preload(:user) |> Repo.one
  end
end

web/views/admin/posting_view.ex
defmodule ElixirStatus.Admin.PostingView do
  use ElixirStatus.Web, :view

  def to_short_uid(permalink) do
    "/p/#{permalink}"
      |> ElixirStatus.URL.from_path
      |> ElixirStatus.LinkShortener.to_uid
  end

  def render("recent.json", %{postings: postings, conn: conn}) do
    data = Enum.map(postings, &to_json(&1, conn))
    %{
      postings: data,
      # TODO: first_time_authors
    }
  end

  def to_json(posting, conn) do
    %{
      id: posting.id,
      published_at: posting.published_at,
      title: posting.title,
      permalink: permalink_posting_path(conn, :show, posting.permalink),
      link_clicks: ElixirStatus.Impressionist.count("postings:#{posting.uid}", "short_link")
    }
  end
end

web/views/posting_view.ex
defmodule ElixirStatus.PostingView do
  use ElixirStatus.Web, :view

end

web/templates/posting/edit.html.eex
<%= link "Back", to: posting_path(@conn, :index), class: "btn btn-back" %>

<%= render "form.html", current_user: current_user(@conn),
                        changeset: @changeset,
                        action: posting_path(@conn, :update, @posting),
                        posting: @posting,
                        conn: @conn,
                        css_class: "edit-post",
                        editing?: true %>

web/templates/posting/form.html.eex
<div class="post <%= @css_class %>">
  <div class="post-avatar">
    <div class="image" style="background-image: url(<%= raw avatar_path(@current_user.user_name) %>)"></div>
  </div>
  <%= form_for @changeset, @action, fn f -> %>
    <%= text_input f, :title, id: "posting_title", class: class_with_error(f, :title, "post-title"), placeholder: "Title goes here (will be tweeted)" %>

    <span class="post-meta">
      <span class="post-date">Today</span>
      <span class="post-author">
        by
        <a href="https://github.com/<%= raw @current_user.user_name %>" target="_blank"><i class="icon-git_circle"></i> <%= raw @current_user.user_name %></a>
        /
        <%= if @current_user.twitter_handle do %>
          <a href="https://twitter.com/<%= raw @current_user.twitter_handle %>" target="_blank"><i class="icon-twitter"></i> <%= raw @current_user.twitter_handle %></a>
          |
          <a href="<%= edit_user_path(@conn, :edit) %>">Edit your profile</a>
        <% else %>
          <a href="<%= edit_user_path(@conn, :edit) %>" class="twitter-related"><i class="icon-twitter"></i> Add your Twitter handle</a>
        <% end %>
      </span>
    </span>

    <%= textarea f, :text, id: "posting_text", class: class_with_error(f, :text, "post-body"), placeholder: "Text should describe what you made in prose. Don't forget to link to your project/blog post!" %>

    <div class="functions">
      <div>
        <small>
          Your post might be edited (typos, wording, etc.)<br>
          You can use Markdown (<a href="#" data-toggle="#formatting-help">formatting help</a>).
        </small>

        <span>
          <a href="#" class="btn btn-preview" data-preview-url="<%= preview_posting_path(@conn, :preview) %>">Preview</a>
          <%= submit "Post this", class: "btn btn-primary" %>
        </span>
      </div>
    </div>

    <div id="formatting-help" style="display: none;">
      <table>
        <tr>
          <th>What you type</th>
          <th>What you get</th>
        </tr>
        <%= for term <- ["[Link](https://github.com/)", "**bold**", "*italics*", "***highlight***", "`inline code`", "Indent with four spaces to render code blocks:\n\n    # This is rendered as a\n    # code block."] do %>
          <tr>
            <td><pre><%= raw term%></pre></td>
            <td><%= sanitized_inline_markdown(term) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  <% end %>

  <%= if @editing? do %>
    <hr>
    <%= link "Delete this posting", to: posting_path(@conn, :delete, @posting), method: :delete, class: "btn btn-danger" %>
  <% end %>
</div>

<div class="preview-post-wrapper"></div>

web/templates/posting/index.html.eex
<div class="posts">
  <%= if logged_in?(@conn) do %>
    <%= if @page_number == 1 do %>
      <%= if @just_signed_in do %>
        <div id="new-post">
          <%= render "form.html", current_user: current_user(@conn),
                                  changeset: @changeset,
                                  action: posting_path(@conn, :create),
                                  conn: @conn,
                                  posting: nil,
                                  css_class: "new-post",
                                  editing?: false %>
        </div>
      <% else %>
        <div class="post sign-in-to-post" id="new-post-btn">
          <div class="post-avatar">
            <div class="image" style="background-image: url(<%= raw avatar_path(current_user(@conn).user_name) %>)"></div>
          </div>
          <a class="btn btn-sign-in" data-toggle="#new-post, #new-post-btn" href="#"><i class="icon-pen"></i> Submit a post</a>
        </div>
        <div id="new-post" style="display: none">
          <%= render "form.html", current_user: current_user(@conn),
                                  changeset: @changeset,
                                  action: posting_path(@conn, :create),
                                  conn: @conn,
                                  posting: nil,
                                  css_class: "new-post",
                                  editing?: false %>
        </div>
      <% end %>
    <% else %>
      <div class="post sign-in-to-post" id="new-post-btn">
        <div class="post-avatar">
          <div class="image" style="background-image: url(<%= raw avatar_path(current_user(@conn).user_name) %>)"></div>
        </div>
        <a class="btn btn-sign-in" href="/postings/new"><i class="icon-pen"></i> Submit another post</a>
      </div>
    <% end %>
  <% else %>
    <div class="post sign-in-to-post">
      <div class="post-avatar">
        <div class="image" style="background-color: #f5f5f5; border: 1px dashed #aaa;"></div>
      </div>
      <a class="btn btn-sign-in" href="/auth"><i class="icon-git"></i> Sign in and post</a>
    </div>
  <% end %>

  <%= if @searching? do %>
    <%= sanitized_inline_markdown "Search results for <code>#{@search_query}</code>" %>
    <a href="/">clear</a>
  <% end %>

  <%= for {posting, index} <- Enum.with_index(@postings) do %>
    <%= render ElixirStatus.PostingView, "posting.html", conn: @conn,
                posting: posting,
                belongs_to_me?: ElixirStatus.Auth.belongs_to_current_user?(@conn, posting),
                just_created_by_me?: @created_posting == posting
                %>
    <%= if index == 2 do %>
      <%= render ElixirStatus.SharedView, "promo_credo.html", conn: @conn %>
    <% end %>
  <% end %>
</div>

<div class="pagination">
  <%= if @page_number > 1 do %>
    <%= link "Previous", to: posting_path(@conn, :index, page: @page_number - 1), class: "pagination-item older" %>
  <% else %>
    <span class="pagination-item older">Previous</span>
  <% end %>
  <%= if @page_number < @total_pages do %>
    <%= link "Next", to: posting_path(@conn, :index, page: @page_number + 1), class: "pagination-item newer" %>
  <% else %>
    <span class="pagination-item newer">Next</span>
  <% end %>
</div>

<div class="search">
  <form method="get" action="/">
    <input type="text" name="q"/ placeholder="Search ...">
  </form>
</div>

web/templates/posting/new.html.eex
<%= link "Back", to: posting_path(@conn, :index), class: "btn btn-back" %>

<h2>New posting</h2>

<%= render "form.html", current_user: current_user(@conn),
                        changeset: @changeset,
                        action: posting_path(@conn, :create),
                        conn: @conn,
                        posting: nil,
                        css_class: "new-post",
                        editing?: false %>

web/templates/posting/posting.html.eex
<div class="post" data-posting-uid="<%= raw @posting.uid %>">
  <div class="post-avatar">
    <div class="image" style="background-image: url(<%= raw avatar_path(@posting.user) %>)"></div>
  </div>

  <h1 class="post-title"><%= link sanitized_inline_markdown(@posting.title), to: permalink_posting_path(@conn, :show, @posting.permalink) %></h1>

  <span class="post-meta">
    <span class="post-date"><%= @posting.published_at |> human_readable_date %></span>
    <span class="post-author">
      by
      <a href="https://github.com/<%= raw @posting.user.user_name %>" target="_blank"><i class="icon-git_circle"></i> <%= raw @posting.user.user_name %></a>
      <%= if @posting.user.twitter_handle do %>
        /
        <a href="https://twitter.com/<%= raw @posting.user.twitter_handle %>" target="_blank"><i class="icon-twitter"></i> <%= raw @posting.user.twitter_handle %></a>
      <% end %>
    </span>

      <span class="functions">
        <%= if @posting.published_tweet_uid do %>
          |
          <a href="https://twitter.com/intent/retweet?tweet_id=<%= @posting.published_tweet_uid %>" target="_blank"><i class="icon-retweet"></i> Retweet this</a>
        <% end %>

        <%= if @belongs_to_me? || admin?(@conn) do %>
          |
          <a href="<%= posting_path(@conn, :edit, @posting) %>"><i class="icon-pen"></i> Edit</a>
        <% end %>

        <%= if admin?(@conn) do %>
          <span class="admin">
            <a href="#" data-toggle="#unpublish-<%= @posting.uid %>"><i class=icon-cross_mark></i></a>
            <span id="unpublish-<%= @posting.uid %>" style="display: none">
              <%= link "Unpublish", to: posting_path(@conn, :unpublish, @posting), method: :post %>
            </span>
          </span>
        <% end %>
      </span>
  </span>

  <div class="post-body">
    <%= sanitized_markdown @posting.text %>
  </div>

  <%= if @just_created_by_me? && @posting.published_tweet_uid do %>
    <div class="post-options">
      <div class="twitter-integration">
        <hr>

        <br>
        <strong>
          <a href="https://twitter.com/<%= twitter_screen_name %>" target="_blank">@<%= twitter_screen_name %></a> just tweeted your post:
        </strong>
        <div class="tweet">
          <a class="btn btn-retweet" style="display: inline-block; float: right;" href="https://twitter.com/intent/retweet?tweet_id=<%= @posting.published_tweet_uid %>" target="_blank"><i class="icon-retweet"></i> Retweet this!</a>
          <%= raw ElixirStatus.Publisher.tweet_text(@posting, @posting.user.twitter_handle) %>
          <div style="clear:both"></div>
        </div>
        <small class="tweet-hint">
          Spread the word: If more people know about this site, more people will read your posts.
        </small>
        <hr>
      </div>
    </div>
  <% end %>
</div>

web/templates/posting/preview.html.eex
<div class="post preview-post">
  <div class="post-avatar">
    <div class="image" style="background-image: url(<%= raw avatar_path(current_user(@conn)) %>)"></div>
  </div>

  <h1 class="post-title"><%= sanitized_inline_markdown(@posting.title) %></h1>

  <span class="post-meta">
    <span class="post-date">PREVIEW</span>
    <span class="post-author">
      by
      <a href="https://github.com/<%= raw current_user(@conn).user_name %>" target="_blank"><i class="icon-git_circle"></i> <%= raw current_user(@conn).user_name %></a>
    </span>
  </span>

  <div class="post-body">
    <%= sanitized_markdown @posting.text %>
  </div>
</div>

web/templates/posting/show.html.eex
<%#= link "Back to frontpage", to: posting_path(@conn, :index), class: "btn btn-back" %>

<div class="post-pagination">
  <%= if @next_posting do %>
    <%= link sanitized_inline_markdown(@next_posting.title), to: permalink_posting_path(@conn, :show, @next_posting.permalink), class: "pagination-item" %>
  <% else %>
    <span class="pagination-item empty"></span>
  <% end %>
  <%= if @prev_posting do %>
    <%= link sanitized_inline_markdown(@prev_posting.title), to: permalink_posting_path(@conn, :show, @prev_posting.permalink), class: "pagination-item" %>
  <% else %>
    <span class="pagination-item empty"></span>
  <% end %>
</div>

<%= render ElixirStatus.PostingView, "posting.html", conn: @conn,
            posting: @posting,
            context: "detail",
            belongs_to_me?: ElixirStatus.Auth.belongs_to_current_user?(@conn, @posting),
            just_created_by_me?: @created_posting == @posting %>

<%= render ElixirStatus.SharedView, "promo_credo.html", conn: @conn %>